pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                sh 'echo checkout'
                checkout scm
            }
        }
        stage('build') {
            steps {
                sh 'echo build'
                sh 'docker build /home/ubuntu/pipelinecontainertest/testcontainer'
            }
         }
         stage('test') {
            steps {
                sh 'echo test'

            }
         }
         stage('publish') {
            steps {
                sh 'echo publish'

            }
        }
    }
}
