pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                sh 'echo checkout'
                checkout scm
            }
        }
        stage('build') {
            steps {
                sh 'echo build'
                sh 'sudo docker build --rm -t testcontainer:latest /home/ubuntu/pipelinecontainertest/testcontainer'
            }
         }
         stage('test') {
            steps {
                sh 'echo test'

            }
         }
         stage('publish') {
            steps {
                sh 'echo publish'
                sh 'echoS login'
                sh 'aws ecr get-login --region ap-northeast-1 --profile ecr --no-include-email > /home/ubuntu/pipelinecontainertest/testcontainer/tmp.txt'
                sh 'chmod u+x tmp.txt'
                sh '`/home/ubuntu/pipelinecontainertest/testcontainer/tmp.txt`'
                sh 'rm /home/ubuntu/pipelinecontainertest/testcontainer/tmp.txt'
                sh 'echo tag'
                sh 'docker tag testcontainer:latest 260863395501.dkr.ecr.ap-northeast-1.amazonaws.com/testrepository:latest'
                sh 'echo push'
                sh 'docker push 260863395501.dkr.ecr.ap-northeast-1.amazonaws.com/testrepository:latest'
            }
        }
    }
}
