pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                sh 'echo checkout'
                checkout scm
            }
        }
        stage('build') {
            steps {
                sh 'echo build'
                sh 'sudo docker build --rm -t flywaycontrainer /home/ubuntu/pipelinecontainertest/flywaycontainer'
            }
         }
         stage('test') {
            steps {
                sh 'echo test'

            }
         }
         stage('run') {
            steps {
                sh 'echo run'
                sh 'sudo docker run flywaycontrainer:latest'

            }
        }
    }
}
